// Get all user chat conversations
export const REQUEST_USER_CHAT_CONVERSATIONS = 'REQUEST_USER_CHAT_CONVERSATIONS'
export const REQUEST_USER_CHAT_CONVERSATIONS_SUCCESS = 'REQUEST_USER_CHAT_CONVERSATIONS_SUCCESS'
export const REQUEST_USER_CHAT_CONVERSATIONS_FAIL = 'REQUEST_USER_CHAT_CONVERSATIONS_FAIL'

// Set active user chat conversation id
export const SET_ACTIVE_USER_CHAT_CONVERSATION_ID = 'SET_ACTIVE_USER_CHAT_CONVERSATION_ID'

// Update massenger
export const ADD_NEW_MESSAGE_IN_THE_CHAT = 'ADD_NEW_MESSAGE_IN_THE_CHAT'

// Get all conversation messages
export const GET_ALL_CONVERSATION_MESSAGES = 'GET_ALL_CONVERSATION_MESSAGES'
export const GET_ALL_CONVERSATION_MESSAGES_SUCCESS = 'GET_ALL_CONVERSATION_MESSAGES_SUCCESS'
export const GET_ALL_CONVERSATION_MESSAGES_FAIL = 'GET_ALL_CONVERSATION_MESSAGES_FAIL'
