// Get all user chat conversations
export const REQUEST_USER_CHAT_CONVERSATIONS = 'REQUEST_USER_CHAT_CONVERSATIONS'
export const REQUEST_USER_CHAT_CONVERSATIONS_SUCCESS = 'REQUEST_USER_CHAT_CONVERSATIONS_SUCCESS'
export const REQUEST_USER_CHAT_CONVERSATIONS_FAIL = 'REQUEST_USER_CHAT_CONVERSATIONS_FAIL'

// Set active user chat conversation id
export const SET_ACTIVE_USER_CHAT_CONVERSATION_ID = 'SET_ACTIVE_USER_CHAT_CONVERSATION_ID'