// Get people nearby by distance
export const REQUEST_GET_PEOPLE_NEARBY = 'REQUEST_GET_PEOPLE_NEARBY'
export const REQUEST_GET_PEOPLE_NEARBY_SUCCESS = 'REQUEST_GET_PEOPLE_NEARBY_SUCCESS'
export const REQUEST_GET_PEOPLE_NEARBY_SUCCESS_FAIL = 'REQUEST_GET_PEOPLE_NEARBY_SUCCESS_FAIL'