// Get people nearby by distance
export const REQUEST_GET_PEOPLE_NEARBY = 'REQUEST_GET_PEOPLE_NEARBY'
export const REQUEST_GET_PEOPLE_NEARBY_SUCCESS = 'REQUEST_GET_PEOPLE_NEARBY_SUCCESS'
export const REQUEST_GET_PEOPLE_NEARBY_SUCCESS_FAIL = 'REQUEST_GET_PEOPLE_NEARBY_SUCCESS_FAIL'

// Get detailed data for profile nearby
export const REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA = 'REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA'
export const REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA_SUCCESS = 'REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA_SUCCESS'
export const REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA_FAIL = 'REQUEST_GET_PROFILE_NEARBY_DETAILED_DATA_FAIL'