// Account Register
export const REQUEST_REGISTER_NEW_ACCOUNT = 'REQUEST_REGISTER_NEW_ACCOUNT'
export const REQUEST_REGISTER_NEW_ACCOUNT_SUCCESS = 'REQUEST_REGISTER_NEW_ACCOUNT_SUCCESS'
export const REQUEST_REGISTER_NEW_ACCOUNT_FAIL = 'REQUEST_REGISTER_NEW_ACCOUNT_FAIL'

// Account login
export const REQUEST_ACCOUNT_LOGIN = 'REQUEST_REGISTER_NEW_ACCOUNT'
export const REQUEST_ACCOUNT_LOGIN_SUCCESS = 'REQUEST_ACCOUNT_LOGIN_SUCCESS'
export const REQUEST_ACCOUNT_LOGIN_FAIL = 'REQUEST_ACCOUNT_LOGIN_FAIL'