// Get my profile details
export const REQUEST_MY_PROFILE_DETAILS = 'REQUEST_MY_PROFILE_DETAILS'
export const REQUEST_MY_PROFILE_DETAILS_SUCCESS = 'REQUEST_MY_PROFILE_DETAILS_SUCCESS'
export const REQUEST_MY_PROFILE_DETAILS_FAIL = 'REQUEST_MY_PROFILE_DETAILS_FAIL'

// Edit my profile details
export const REQUEST_EDIT_MY_PROFILE_DETAILS = 'EDIT_MY_PROFILE_DETAILS'
export const REQUEST_EDIT_MY_PROFILE_DETAILS_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS'
export const REQUEST_EDIT_MY_PROFILE_DETAILS_FAIL = 'EDIT_MY_PROFILE_FAIL'