// Get my profile details
export const REQUEST_MY_PROFILE_DETAILS = 'REQUEST_MY_PROFILE_DETAILS'
export const REQUEST_MY_PROFILE_DETAILS_SUCCESS = 'REQUEST_MY_PROFILE_DETAILS_SUCCESS'
export const REQUEST_MY_PROFILE_DETAILS_FAIL = 'REQUEST_MY_PROFILE_DETAILS_FAIL'

// Edit my profile details
export const REQUEST_EDIT_MY_PROFILE_DETAILS = 'EDIT_MY_PROFILE_DETAILS'
export const REQUEST_EDIT_MY_PROFILE_DETAILS_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS'
export const REQUEST_EDIT_MY_PROFILE_DETAILS_FAIL = 'EDIT_MY_PROFILE_FAIL'

// Profile active on/off
export const UPDATE_USER_PROFILE_BOOLEAN_FIELD = 'UPDATE_USER_PROFILE_BOOLEAN_FIELD'
export const UPDATE_USER_PROFILE_BOOLEAN_FIELD_SUCCESS = 'UPDATE_USER_PROFILE_BOOLEAN_FIELD_SUCCESS'

// Upload avatar image
export const REQUEST_UPLOAD_AVATAR_IMAGE = 'REQUEST_UPLOAD_AVATAR_IMAGE'
export const REQUEST_UPLOAD_AVATAR_IMAGE_SUCCESS = 'REQUEST_UPLOAD_AVATAR_IMAGE_SUCCESS'
export const REQUEST_UPLOAD_AVATAR_IMAGE_FAIL = 'REQUEST_UPLOAD_AVATAR_IMAGE_FAIL'

// Update user profile text field
export const UPDATE_USER_PROFILE_TEXT_FIELD = 'UPDATE_USER_PROFILE_TEXT_FIELD'
export const UPDATE_USER_PROFILE_TEXT_FIELD_SUCCESS = 'UPDATE_USER_PROFILE_TEXT_FIELD_SUCCESS'

// Get geolocation
export const GET_USER_GEOLOCATION = 'GET_USER_GEOLOCATION'
export const GET_USER_GEOLOCATION_SUCCESS = 'GET_USER_GEOLOCATION_SUCCESS'
export const GET_USER_GEOLOCATION_FAIL = 'GET_USER_GEOLOCATION_FAIL'

// Update user profile geaolocation
export const UPDATE_USER_PROFILE_GEOLOCATION = 'UPDATE_USER_PROFILE_GEOLOCATION'
export const UPDATE_USER_PROFILE_GEOLOCATION_SUCCESS = 'UPDATE_USER_PROFILE_GEOLOCATION_SUCCESS'
export const UPDATE_USER_PROFILE_GEOLOCATION_FAIL = 'UPDATE_USER_PROFILE_GEOLOCATION_FAIL'

// Add Country Language
export const ADD_COUNTRY_LANGUAGE = 'ADD_COUNTRY_LANGUAGE'
export const ADD_COUNTRY_LANGUAGE_SUCCESS = 'ADD_COUNTRY_LANGUAGE_SUCCESS'

// Delete Country Language
export const DELETE_COUNTRY_LANGUAGE = 'DELETE_COUNTRY_LANGUAGE'

// Upload User Profile Image
export const UPLOAD_USER_PROFILE_IMAGE = 'UPLOAD_USER_PROFILE_IMAGE'
export const UPLOAD_USER_PROFILE_IMAGE_SUCCESS = 'UPLOAD_USER_PROFILE_IMAGE_SUCCESS'
export const UPLOAD_USER_PROFILE_IMAGE_FAIL = 'UPLOAD_USER_PROFILE_IMAGE_FAIL'

// DELETE User Profile Image
export const DELETE_USER_PROFILE_IMAGE = 'DELETE_USER_PROFILE_IMAGE'
export const DELETE_USER_PROFILE_IMAGE_SUCCESS = 'DELETE_USER_PROFILE_IMAGE_SUCCESS'
export const DELETE_USER_PROFILE_IMAGE_FAIL = 'DELETE_USER_PROFILE_IMAGE_FAIL'

